### ISSUE TITLE
Testing Branch - seeing encoding error 

### ISSUE THREAD

**Issue by everetteallen** [jssimporter/Spruce#10]
So with:
defaults read com.github.autopkg
2015-08-28 10:03:45.945 defaults[45503:11294452] 
Domain com.github.autopkg does not exist
and
defaults read com.github.sheagcraig.python-jss.plist jss_url
https://nc.jamfcloud.com:443/
I get an encode error on testing branch.

/Desktop/Spruce-testing/spruce.py --apps -v
🌲  Building: Mobile Apps... 🌲
Traceback (most recent call last):
  File "/Users/ega/Desktop/Spruce-testing/spruce.py", line 1798, in <module>
    main()
  File "/Users/ega/Desktop/Spruce-testing/spruce.py", line 1794, in main
    run_reports(args)
  File "/Users/ega/Desktop/Spruce-testing/spruce.py", line 1731, in run_reports
    results.append(func(*_args_dict))
  File "/Users/ega/Desktop/Spruce-testing/spruce.py", line 1147, in build_apps_report
    page = session.get(external_url).text
  File "/Library/Python/2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 477, in get
    return self.request('GET', url, *_kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 451, in request
    prep = self.prepare_request(req)
  File "/Library/Python/2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 382, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Library/Python/2.7/site-packages/requests-2.7.0-py2.7.egg/requests/models.py", line 304, in prepare
    self.prepare_url(url, params)
  File "/Library/Python/2.7/site-packages/requests-2.7.0-py2.7.egg/requests/models.py", line 362, in prepare_url
    to_native_string(url, 'utf8')))
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

**Comment by grahampugh** [comment]
Please try latest version
