### ISSUE TITLE
Error deleting packages

### ISSUE THREAD

**Issue by MScottBlake** [jssimporter/Spruce#15]
My master DP is a JDS. There are other File Share DPs, but the configured option is that JDS. I do it this way because I have automated processes to distribute content to the other shares and it's faster than uploading from my client machine.

I am getting the following when I try to remove packages:

```
computername:Spruce username$ ./spruce.py --remove removals.xml
Are you sure you want to continue deleting objects from https://casper.domain.com? (Y or N): y
Package object 1887: Adobe Shockwave Player-12.2.3r183.pkg deleted.
Traceback (most recent call last):
  File "./spruce.py", line 1931, in <module>
    main()
  File "./spruce.py", line 1925, in main
    remove(removal_tree)
  File "./spruce.py", line 1875, in remove
    jss_connection.distribution_points.delete(item.text)
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/distribution_points.py", line 273, in delete
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/distribution_point.py", line 730, in delete
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/jamf_software_server.py", line 589, in Package
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/jamf_software_server.py", line 736, in get_object
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/jamf_software_server.py", line 811, in get_individual_object
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/jamf_software_server.py", line 202, in get
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/tools.py", line 87, in error_handler
jss.exceptions.JSSGetError: Response Code: 404  Response: Not Found. The server has not found anything matching the request URI
```

It does remove the package properly, but only does one then fails.

I was looking through the code and it looks like it's polling the JSS for its DPs rather than look at what is configured. Unfortunately, I don't know enough to actually fix it.

**Comment by homebysix** [comment]
@MScottBlake Can you try to reproduce this error again using the current "testing" branch of Spruce?

**Comment by smithjw** [comment]
@homebysix I've been seeing the same errors. Tried the Testing branch and getting the same errors

```python spruce.py --remove OldPkgs.xml
Are you sure you want to continue deleting objects from https://jss.cultureamp.net? (Y or N): y
Package object 40: Bartender-2.1.6.pkg deleted.
Traceback (most recent call last):
  File "spruce.py", line 1955, in <module>
    main()
  File "spruce.py", line 1949, in main
    remove(removal_tree)
  File "spruce.py", line 1892, in remove
    jss_connection.distribution_points.delete(filename)
  File "/Library/Python/2.7/site-packages/python_jss-1.5.0-py2.7.egg/jss/distribution_points.py", line 273, in delete
  File "/Library/Python/2.7/site-packages/python_jss-1.5.0-py2.7.egg/jss/distribution_point.py", line 730, in delete
  File "/Library/Python/2.7/site-packages/python_jss-1.5.0-py2.7.egg/jss/jssobject.py", line 308, in delete
  File "/Library/Python/2.7/site-packages/python_jss-1.5.0-py2.7.egg/jss/jamf_software_server.py", line 314, in delete
  File "/Library/Python/2.7/site-packages/python_jss-1.5.0-py2.7.egg/jss/tools.py", line 89, in error_handler
jss.exceptions.JSSDeleteError: Response Code: 404	Response: Not Found. The server has not found anything matching the request URI```

Packages are stored in a CDP on S3

**Comment by grahampugh** [comment]
@MScottBlake @smithjw Please try the latest release. It's designed to be compatible with your JSSImporter installation.
