### ISSUE TITLE
does not work with SSO enabled

### ISSUE THREAD

**Issue by mrmte** [jssimporter/Spruce#22]
followed all the guides, used before in the past no issue. OS 10.12.4 beta 5

tim.kimpton$ python /Users/tim.kimpton/Downloads/Spruce-master/spruce.py --packages -o cruftypackages.xml
🌲  Building: Package Report... 🌲
Traceback (most recent call last):
  File "/Users/tim.kimpton/Downloads/Spruce-master/spruce.py", line 1955, in <module>
    main()
  File "/Users/tim.kimpton/Downloads/Spruce-master/spruce.py", line 1951, in main
    run_reports(args)
  File "/Users/tim.kimpton/Downloads/Spruce-master/spruce.py", line 1747, in run_reports
    results.append(func(**args_dict))
  File "/Users/tim.kimpton/Downloads/Spruce-master/spruce.py", line 732, in build_packages_report
    subset=["general", "package_configuration", "packages"])
  File "/Library/Python/2.7/site-packages/jss/jssobjectlist.py", line 179, in retrieve_all
    in self]
  File "/Library/Python/2.7/site-packages/jss/jssobjectlist.py", line 66, in id
    return int(self["id"])
  File "/Library/Python/2.7/site-packages/jss/jssobjectlist.py", line 38, in __getitem__
    return self.store[key]
KeyError: 'id'

**Comment by mrmte** [comment]
Hi still cannot get this working. Please can you help?

**Comment by mrmte** [comment]
discovered the issue but do not know how to fix it. This does not work if you have sso enabled in your JSS and failover URL does not work :(

**Comment by mrmte** [comment]
fixed, just created a standard account in the jss and im using that instead now it works :)
