### ISSUE TITLE
Error when trying to remove packages from provided xml

### ISSUE THREAD

**Issue by smashism** [jssimporter/Spruce#42]
Here is the error I see:
```autopkg@15:03:02:~$ python /Users/autopkg/Downloads/Spruce-master/spruce.py --remove /Users/autopkg/Desktop/packages20190903.xml 
JSS: https://JSSServer.com
Preferences used: ~/Library/Preferences/com.github.autopkg.plist
Are you sure you want to continue deleting objects from https://JSSServer.com? (Y or N): y
Traceback (most recent call last):
  File "/Users/autopkg/Downloads/Spruce-master/spruce.py", line 2054, in <module>
    main()
  File "/Users/autopkg/Downloads/Spruce-master/spruce.py", line 2048, in main
    remove(removal_tree)
  File "/Users/autopkg/Downloads/Spruce-master/spruce.py", line 1936, in remove
    except jss.JSSGetError as error:
AttributeError: 'module' object has no attribute 'JSSGetError'```

I have the latest JSSImporter + python-jss and am using the newest release of spruce.

**Comment by grahampugh** [comment]
Hi @smashism I just pushed a commit that should fix this. `jss.JSSGetError` changed to `jss.GetError` in python-jss 2.0.0.

**Comment by smashism** [comment]
The latest commit fixes this issue.
