### ISSUE TITLE
Issue with the remove.xm file and command

### ISSUE THREAD

**Issue by kylejericson** [jssimporter/Spruce#47]
I get this error trying to run the remove command 

administrator@AutoPKG ~ % sudo /usr/bin/python /usr/local/bin/spruce.py --remove /Users/administrator/Desktop/remove2.xml
JSS: https://myorg.jamfcloud.com
Preferences used: ~/Library/Preferences/com.github.autopkg.plist
Are you sure you want to continue deleting objects from https://myorg.jamfcloud.com? (Y or N): Y
Traceback (most recent call last):
  File "/usr/local/bin/spruce.py", line 2249, in <module>
    main()
  File "/usr/local/bin/spruce.py", line 2243, in main
    remove(removal_tree)
  File "/usr/local/bin/spruce.py", line 2069, in remove
    if not check_with_user():
  File "/usr/local/bin/spruce.py", line 2188, in check_with_user
    "from %s? (Y or N): " % jss_connection.base_url)
  File "<string>", line 1, in <module>
NameError: name 'Y' is not defined

**Comment by kylejericson** [comment]
Ran with python3 fixed the issue my bad.  /usr/local/autopkg/python
