### ISSUE TITLE
Getting error from current testing branch 08122015...

### ISSUE THREAD

**Issue by everetteallen** [jssimporter/Spruce#5]
I know it is testing but just FYI seeing this error on subset with any flag.

leeta:Spruce-testing ega$ /Users/ega/Downloads/Spruce-testing/spruce.py -t -v
🌲  Building: Policy Report... 🌲
Traceback (most recent call last):
  File "/Users/ega/Downloads/Spruce-testing/spruce.py", line 1373, in <module>
    main()
  File "/Users/ega/Downloads/Spruce-testing/spruce.py", line 1369, in main
    run_reports(args)
  File "/Users/ega/Downloads/Spruce-testing/spruce.py", line 1316, in run_reports
    results.append(func(**args_dict))
  File "/Users/ega/Downloads/Spruce-testing/spruce.py", line 798, in build_policies_report
    subset=["general", "scope"])
TypeError: retrieve_all() got an unexpected keyword argument 'subset'

**Comment by everetteallen** [comment]
Nevermind, have to be running the testing branch of python-jss of course.

**Comment by sheagcraig** [comment]
I'm hoping to release both Spruce and the python-jss required for it TODAY.

**Comment by everetteallen** [comment]
I was going to try to test for you but got pulled away by a fire.  I just jumped the gun because I did not read the diffs.  Sorry.
